### ISSUE TITLE
Open assets for game engine recreations.

### ISSUE THREAD

**Issue by publicsite** [open-source-ideas/ideas#338]
Hi,

There is a huge list of game engine recreations that could be freed, if only they had open source assets (artwork).

[https://en.wikipedia.org/wiki/List_of_game_engine_recreations
](https://en.wikipedia.org/wiki/List_of_game_engine_recreations
)

Ideally what needs to be done, is to create new artwork/assets for these game recreations; artwork/assets that is free/libre and artwork that is NOT based on the existing artwork in any way.

If people work on this, we may find that we have some more libre games we could play.

**Comment by KOLANICH** [comment]
It won't be those games. The most of games are assets. If you replace an engine of GTA from a proprietary one to reVC/re3, it still will be GTA 3/VC. If you replace the assets keeping the engine intact ... it will be a completely different game with an own story, gameplay and atmosphere.

**Comment by KOLANICH** [comment]
An engine to a game assets bundle is like a purpose-built cinema projector to an unique bobbin of film. People play exact games for the exact games. Not for the engine. The open source engine recreatiins are done to use them on specific games. If they wanted to make a brand new game, they would have taken some hi-end open source game engine and made assets for it instead of reversing the original engine.

**Comment by publicsite** [comment]
Well that's all well and good, but doesn't explain why zdoom exists. XD

**Comment by KOLANICH** [comment]
zdoom can use the original assets, cannot it?

**Comment by publicsite** [comment]
Like my car can run on vegetable oil.

**Comment by FredrikAugust** [comment]
Hi, please use the idea template provided when opening issues. Either add the template to this issue, or create a new one:)
