### ISSUE TITLE
Document licensing considerations

### ISSUE THREAD

**Issue by aschrijver** [open-source-ideas/ideas#345]
Without licensing instructions added to this repo, every idea dropped here is effectively "Copyright [author], all rights reserved".

Whether that is the intention or not, it should be documented in the README.

At this moment with so many ideas already added, you can't drop a LICENSE on the repo anymore. But you could update the issue template with some options the issue creator can choose from and e.g. default to CC-BY or CC-BY-SA with some README explainer that means.

**Comment by KOLANICH** [comment]
I doubt that ideas by themselves are copyrightable, text expressing them can be copyrightable, but the ideas themselves are not. But they are usually patentable if one gives enough money to the needed people within the power hierarchy as a kickback, and everyone will have then hard time to dispute the patent if they wanted.

From the other side FOSS ideas are mostly useless for patent lawsuits because they are grassroots initiatives to make people lives more comfortable rather than to make a lot of money (if one wants to make a lot of money on an idea, the last thing he will do is publishing it in the list of ideas where people ask each other to implement their ideas) and patent trolls usually sue the ones who have money to pay them for protection.

BTW, this issue belongs to `meta` repository.

**Comment by aschrijver** [comment]
Thanks, I should have been more clear. The text is copyrighted. It doesn't decrease the need for a license, though.

**Comment by FredrikAugust** [comment]
I believe the meta-repository was deleted in favour of the "Discussions" feature — so if this is something you wish to discuss further please create a discussion there:)

I don't know much about the subject, so it's unlikely that something will be done about it.
